version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      # Avoid setting up Git in the container
      - ~/.gitconfig:/root/.gitconfig
      # Avoids setting up ssh in container
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    links:
      - postgres
      - mongo
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=server
  mongo:
    image: mongo:latest
    volumes:
      - /data/db

